name: build-github-pages
on:
  workflow_dispatch:
  push:
    branches:
      - master
    paths:
      - docs/**

jobs:
  build:
    name: Deploy docs
    runs-on: ubuntu-latest
    steps:
      - name: Checkout main
        uses: actions/checkout@v2
      
      - name: install mkdocs
        run: |
          echo 'mkdocs' > requirements.txt
          echo 'numpy' >> requirements.txt
        

      - name: Deploy docs
        uses: mhausenblas/mkdocs-deploy-gh-pages@nomaterial
        env:
          GITHUB_TOKEN: ${{ secrets.DEPLOY_DOCS }}
          CONFIG_FILE: mkdocs.yml
